sparksys:
  swagger:
    group-name: activiti流程引擎模块
    base-package: com.sparksys.activiti.interfaces
    api-info:
      title: activiti流程引擎模块
      description: activiti流程引擎管理
      terms-of-service-url: https://www.sparksys.top
      version: 1.0
server:
  port: 8080
  undertow:
    buffer-size: 1024
    direct-buffers: on
    always-set-keep-alive: true
spring:
  application:
    name: sparksys-activiti
  # 数据库配置
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://rm-bp1cp68o8t1gq604p5o.mysql.rds.aliyuncs.com/activiti?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: zhouxinlei
    password: zxl298828
  #activiti配置
  activiti:
    database-schema-update: true
    check-process-definitions: false
    #history-level: full
    #activiti7 添加这个配置，才会生成25张表，否则只有17张
    #activiti6可以不添加，但是第一次启动只有16张表，启动两次才有26张表
    #db-history-used: true
  redis:
    host: 47.114.40.129
    port: 6379
    time-out: 28800
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: 200
        min-idle: 0
    redisson:
      config: classpath:redisson.yaml
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.sparksys.activiti.infrastructure.entity
  mapperScan: com.sparksys.activiti.infrastructure.mapper
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com.sparksys.activiti.infrastructure.mapper: debug
  file:
    #path: /Users/zhouxinlei/logs
    path: C:\logs


