sparksys:
  swagger:
    group-name: activiti流程引擎模块
    base-package: com.sparksys.activiti.interfaces
    api-info:
      title: activiti流程引擎模块
      description: activiti流程引擎管理
      termsOfServiceUrl: https://www.sparksys.top
      version: 1.0
server:
  port: 8080
  undertow:
    buffer-size: 1024
    direct-buffers: on
    always-set-keep-alive: true
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.116.52.58:3306/activiti?useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: Farben.2020
  #activiti配置
  activiti:
    database-schema-update: true
    check-process-definitions: false
    #history-level: full
    #activiti7 添加这个配置，才会生成25张表，否则只有17张
    #activiti6可以不添加，但是第一次启动只有16张表，启动两次才有26张表
    #db-history-used: true
  #freemarker模板配置
  freemarker:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    tempalte-loader-path: classpath:/templates
#配置日志
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
    com.sparksys.activiti.infrastructure.mapper: debug
  file:
    #path: /Users/zhouxinlei/logs
    path: C:\logs
# mybatis的xml查询文件和实体类位置配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.sparksys.activiti.infrastructure.entity
  mapperScan: com.sparksys.activiti.infrastructure.mapper
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# 启动工程部署流程标识
process:
  deploy: false



